
homeassistant:
  name: Home Assistant
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  elevation: !secret location_elevation
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  external_url: !secret external_url
  internal_url: !secret internal_url

http:
  ip_ban_enabled: false

config:

frontend:
  themes: !include_dir_merge_named themes/

lovelace: !include lovelace.yaml

mobile_app:

history:
  use_include_order: True
  include: !include history.yaml

recorder:
  db_url: !secret ha_recorder_db_url
  include: !include recorder.yaml
  auto_purge: false

logbook:
  include: !include logbook.yaml

person:

ssdp:

sun:

system_health:

zeroconf:

stream:

device_tracker:
  - platform: aruba
    host: !secret aruba_host
    username: !secret aruba_username
    password: !secret aruba_password
    new_device_defaults:
      track_new_devices: false

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscriber_id

fibaro:
  gateways:
    - url: !secret fibaro_url
      username: !secret fibaro_username
      password: !secret fibaro_password

speedtestdotnet:

weather:
  - platform: buienradar
    name: IJsselstein

automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
camera: !include camera.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_select: !include input_select.yaml
light: !include light.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
timer: !include timer.yaml
zone: !include zones.yaml
